entitySpawnDupes: 3
dupeHostilesOnly: true
logItemsReceivedInConsole: false
eventDelay: 800
newIslandCommandDelay: 36000
islandDistance: 1250
islandGenHeight: 120
enableBedSpawn: true
giveWormholeOnNewSpawn: true
newIslandItemBonus: 10
newIslandEventBonus: 5
overworld: 'world'
nether: 'world_nether'
end: 'world_the_end'