entitySpawnDupes: 3
dupeHostilesOnly: true
logItemsReceivedInConsole: false
eventDelay: 800
newIslandCommandDelay: 36000
islandDistance: 1024
islandGenHeight: 120
enableBedSpawn: false
giveWormholeOnNewSpawn: true
newIslandItemBonus: 5
newIslandEventBonus: 5
overworld: 'world'
nether: 'world_nether'
end: 'world_the_end'